# Generated by Django 5.2 on 2025-09-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('academic_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KitItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.variant')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kits')),
            ],
        ),
    ]
