# Generated by Django 5.2 on 2025-10-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0009_alter_student_admission_year'),
        ('stock', '0011_variant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=50)),
                ('description', models.CharField(blank=True, max_length=254)),
                ('academic_year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
            },
        ),
        migrations.CreateModel(
            name='KitItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.variant')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kits')),
            ],
            options={
                'verbose_name': 'Kit Item',
                'verbose_name_plural': 'Kit Items',
            },
        ),
        migrations.CreateModel(
            name='KitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.student')),
                ('kititems', models.ManyToManyField(to='kits.kititems')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kits')),
            ],
            options={
                'verbose_name': 'Kit Allocation',
                'verbose_name_plural': 'Kit Allocations',
            },
        ),
    ]
