# Generated by Django 5.2 on 2025-10-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kits', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kititems',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.variant'),
        ),
        migrations.AddField(
            model_name='kitallocation',
            name='kititems',
            field=models.ManyToManyField(to='kits.kititems'),
        ),
        migrations.AddField(
            model_name='kititems',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kits'),
        ),
        migrations.AddField(
            model_name='kitallocation',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kits'),
        ),
    ]
