# Generated by Django 5.2 on 2025-08-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
