# Generated by Django 5.2 on 2025-11-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returns',
            name='condition',
        ),
    ]
