# Generated by Django 5.2 on 2025-09-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kititems',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='kititems',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Kits',
        ),
        migrations.DeleteModel(
            name='KitItems',
        ),
    ]
