# Generated by Django 5.2 on 2025-11-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='photo',
            field=models.ImageField(blank=True, default='variant/default.jpg', upload_to='variant/'),
        ),
    ]
