# Generated by Django 5.2 on 2025-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_issueitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
