# Generated by Django 5.2 on 2025-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_student_enrollement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='student',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='stock.item'),
        ),
    ]
