# Generated by Django 5.2 on 2025-09-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_vendor_address_alter_vendor_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='supplier',
        ),
    ]
