# Generated by Django 5.2 on 2025-05-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_transaction_options_student_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='items',
        ),
    ]
