# Generated by Django 5.2 on 2025-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_vendor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='invoice_file',
            field=models.ImageField(blank=True, null=True, upload_to='invoice/'),
        ),
    ]
