# Generated by Django 5.2 on 2025-09-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceipt',
            old_name='recieved_data',
            new_name='recieved_date',
        ),
    ]
