# Generated by Django 5.2 on 2025-09-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_purchase_discount_alter_purchase_tax_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_type',
        ),
    ]
