# Generated by Django 5.2 on 2025-10-03 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_category_cat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocations',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
