# Generated by Django 5.2 on 2025-05-27 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='payment',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's name"),
        ),
        migrations.AddField(
            model_name='student',
            name='receipt',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollement',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
