# Generated by Django 5.2 on 2025-09-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_recieved_data_goodsreceipt_recieved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='satatus',
            new_name='status',
        ),
    ]
