# Generated by Django 5.2 on 2025-05-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_rename_payment_purchase_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='supplier_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier Location'),
        ),
    ]
