# Generated by Django 5.2 on 2025-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_allocations_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocations',
            options={'verbose_name_plural': 'Allocations'},
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='txn_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=50),
        ),
    ]
