# Generated by Django 5.2 on 2025-05-29 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_purchase_supplier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\+?\\d{2})?\\d{10}$')]),
        ),
    ]
