# Generated by Django 5.2 on 2025-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_allocations_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returns',
            options={'verbose_name_plural': 'Returns'},
        ),
        migrations.AlterModelOptions(
            name='stocktransactions',
            options={'ordering': ['-txn_date']},
        ),
        migrations.AlterField(
            model_name='stocktransactions',
            name='txn_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
