# Generated by Django 5.2 on 2025-10-04 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_returns_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
