# Generated by Django 5.2 on 2025-05-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_issue_send_message_student_date_of_birth_returnkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.student'),
        ),
    ]
