# Generated by Django 5.2 on 2025-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_returns_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
