# Generated by Django 5.2 on 2025-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_returns_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='variant/'),
        ),
    ]
