# Generated by Django 5.2 on 2025-06-09 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_purchase_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnkit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Collector'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollement',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='receipt',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$')]),
        ),
    ]
