# Generated by Django 5.2 on 2025-10-11 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_variant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^(\\+?\\d{2})?\\d{10}$')]),
        ),
    ]
