# Generated by Django 5.2 on 2025-06-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_returnkit_user_alter_student_enrollement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnKit',
        ),
    ]
