# Generated by Django 5.2 on 2025-10-11 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_vendor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, error_messages={'wrong-phone': 'Please enter a valid mobile number. Example +919988776633 or 7925666666'}, max_length=50, validators=[django.core.validators.RegexValidator('^(\\+?\\d{2})?\\d{10}$')]),
        ),
    ]
