# Generated by Django 5.2 on 2025-06-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_delete_returnkit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
    ]
