# Generated by Django 5.2 on 2025-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='update_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
