# Generated by Django 5.2 on 2025-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_stock_update_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='movement_type',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Move Up'), (3, 'Move Down')], default=1),
        ),
    ]
