# Generated by Django 5.2 on 2025-10-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_stock_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='movement_type',
            field=models.PositiveIntegerField(choices=[(1, 'New'), (2, 'Move Up'), (3, 'Move Down'), (4, 'Adjustment')], default=1),
        ),
    ]
