# Generated by Django 5.2 on 2025-10-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_stock_movement_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='update_quantity',
        ),
    ]
