# Generated by Django 5.2 on 2025-10-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_remove_stock_update_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='movement_type',
            field=models.PositiveIntegerField(choices=[(1, 'In'), (2, 'Out'), (3, 'Return'), (4, 'Adjustment')], default=1),
        ),
    ]
