# Generated by Django 5.2 on 2025-05-16 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockuser',
            name='emp_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Employee ID'),
        ),
    ]
