# Generated by Django 5.2 on 2025-06-17 04:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_stockuser_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockuser',
            name='phone',
            field=models.CharField(default='79222222555', max_length=15, validators=[django.core.validators.RegexValidator('^(\\+\\d{2})?\\d{10}', message='Please enter the valid mobile number. Example +919999998888 or 7925666666')]),
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
