# Generated by Django 5.2 on 2025-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_stockuser_phone_otpcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'verbose_name_plural': 'OTPs'},
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
