# Generated by Django 5.2 on 2025-09-20 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^(\\+\\d{2})?\\d{10}$', message='Please enter a valid mobile number. Example +919999998888 or 7925666666')]),
        ),
    ]
