# Generated by Django 5.2 on 2025-09-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_user_phone_employee_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
