# Generated by Django 5.2 on 2025-10-12 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_student_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^(\\+?\\d{2})?\\d{10}$', message='Please enter a valid mobile number. Example +919999998888 or 7925666666')]),
        ),
    ]
